platform :ios, ‘8.0’

target 'GDMap' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'Masonry'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'AMap3DMap-NO-IDFA' #3D地图,不涉及IDFA功能
pod 'AMapSearch-NO-IDFA' #地图搜索,不涉及IDFA功能
pod 'AMapLocation-NO-IDFA' #地图定位,不涉及IDFA功能

  target 'GDMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GDMapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
